### ISSUE TITLE
Bottom Navigation View stops working after theme change

### ISSUE THREAD

**Issue by shrek-gabe-itch** [jahirfiquitiva/Frames#174]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version.

### Device/App info:
 - Frames Version: `3.2.9`
 - Android version: `9`
 - Device Manufacturer: `OnePlus`
 - Device Name: `5`

### Describe the bug
After changing the application theme between dark and light, Bottom Navigation View stops working. Also, the Bottom Navigation View overlaps the lowest row of wallpaper cards. After restart everything works as it should.

### Reproduction Steps
1. Open Frames settings.
2. Click Appearance, change theme to dark or light.
3. Go to the Frames main screen and try changing the tab.

### Expected behavior
Tabs should change.

### Screenshots & Video
![Screenshot_20200518-112912](https://user-images.githubusercontent.com/58945139/82181133-5fd18000-98fb-11ea-8fb3-611c8b622cd6.jpg)

[**Video**](https://youtu.be/_hBNc65w7SQ)

### Additional context
Blueprint has the same bug.

**Comment by evowizz** [comment]
After digging into this issue, I finally found where and why it's caused.

### Where?

It looks like it's caused by the following lines: https://github.com/jahirfiquitiva/Frames/blob/69c0f68f800b36798e37b3b60e7098c298d6ce5b/library/src/main/kotlin/dev/jahir/frames/ui/fragments/base/BaseFramesFragment.kt#L33-L36

As seen below, the method `setupContentBottomOffset()` uses the bottom navigation view to adjust the bottom offset.
https://github.com/jahirfiquitiva/Frames/blob/69c0f68f800b36798e37b3b60e7098c298d6ce5b/library/src/main/kotlin/dev/jahir/frames/ui/fragments/base/BaseFramesFragment.kt#L72-L78

`bottomNavigation` is a lazy defined by the extension `findView()`.

https://github.com/jahirfiquitiva/Frames/blob/69c0f68f800b36798e37b3b60e7098c298d6ce5b/library/src/main/kotlin/dev/jahir/frames/ui/activities/base/BaseSystemUIVisibilityActivity.kt#L22

### Why?
After changing the theme, pressing back resumes the previous Activity. But because the theme was updated, this causes the activity to be recreated by either the AndroidX AppCompat lib or directly Android (I haven't looked into that). AndroidX's `FragmentActivity` then restore the Fragments itself (see: [FragmentActivity:234-236](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-master-dev:fragment/fragment/src/main/java/androidx/fragment/app/FragmentActivity.java;l=234-236;drc=8316b2c3626b7fca24205299f14e84b83265b733))  and so, `onAttach` (in the Fragment) is called before `setContentView` (in the Activity). After that `bottomNavigation` returns null, and because it's a Lazy, it will remain null.

Finally, in the line below, `setOnNavigationItemSelectedListener()` is not called because it's used on `bottomNavigation?` which — as mentioned above — returns null. If `bottomNavigation?` was replaced by `bottomNavigation!!`, Frames would crash.

https://github.com/jahirfiquitiva/Frames/blob/69c0f68f800b36798e37b3b60e7098c298d6ce5b/library/src/main/kotlin/dev/jahir/frames/ui/activities/FramesActivity.kt#L55

**Note:** In [Blueprint](https://github.com/jahirfiquitiva/Blueprint) (which uses Frames), `HomeFragment` and `RequestFragment` are not impacted. This is because `HomeFragment` directly extends `Fragment`. As for `RequestFragment` — while it extends `BaseFramesFragment` — it also overrides `setupContentBottomOffset()` which doesn't call `bottomNavigation` because the parameter `view` is null and `getView()` also returns null when `onAttach()` is called. So `setContentView()` is still called before `bottomNavigation`.
