### ISSUE TITLE
How do i get my key.

### ISSUE THREAD

**Issue by arjunmaan2011** [jahirfiquitiva/Frames#4]
You Said "your key value here" in https://github.com/jahirfiquitiva/Frames-Sample/wiki/Enable-License-Check From Where i have to get that key any links.

**Comment by jahirfiquitiva** [comment]
1. Go to (dev console](https://play.google.com/apps/publish/).
2. Select your application
3. Select `Development Tools` Option
4. Select `API and Services` Option
5. Look for your License Key there
6. Copy and paste in the app code as explained in the wiki.

**Note:** Real section/option names may differ. These were translated by me from Spanish, because I don't see the console in English.
